name: CI Build and Push

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build backend (API) image
      - name: Build and push Backend Docker image
        run: |
          IMAGE=myLedger-backend:${{ github.sha }}
          docker build -f apps/backend/Dockerfile -t $IMAGE apps/backend
          docker push $IMAGE

      # Build worker image
      - name: Build and push Worker Docker image
        run: |
          IMAGE=myLedger-worker:${{ github.sha }}
          docker build -f apps/worker/Dockerfile -t $IMAGE apps/worker
          docker push $IMAGE

      # Update GitOps repo
      - name: Update manifests repo (GitOps)
        run: |
          git clone https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/Kiteretzu/myledger-k8s.git
          cd myledger-k8s
          # Update backend deployment
          sed -i "s|image: myapp-backend:.*|image: myapp-backend:${{ github.sha }}|" deployment-backend.yaml
          # Update worker deployment
          sed -i "s|image: myapp-worker:.*|image: myapp-worker:${{ github.sha }}|" deployment-worker.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update images to SHA ${{ github.sha }}"
          git push