name: CI Build and Push

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=myapp:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Update manifests repo (GitOps)
        run: |
          git clone https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/Kiteretzu/myledger-k8s.git
          cd myledger-k8s
          IMAGE=myapp:${{ github.sha }}
          # Update deployment.yaml image tag
          sed -i "s|image: .*$|image: $IMAGE|" deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to $IMAGE"
          git push